# Generated by Django 5.1.2 on 2025-02-05 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_company_options_invitation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
