# Generated by Django 5.1.2 on 2025-02-13 02:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Key')),
                ('accepted', models.BooleanField(blank=True, default=False, verbose_name='Accepted')),
                ('sent', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sent')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('inviter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
